version: "3"
services:
  myapp:
    image: ghcr.io/nlmatics/nlm-ingestor:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '0.25'
          memory: 128M
    ports:
    - target: 5001
      published: __PORT__
    extra_hosts:
      host.docker.internal: host-gateway
